allow unpacking multiple files

diff --git a/bin/unpack-supportconfig b/bin/unpack-supportconfig
--- a/bin/unpack-supportconfig
+++ b/bin/unpack-supportconfig
@@ -1,17 +1,23 @@
 #!/bin/bash
 
-if ! dir=$(up "$1"); then
-    exit $?
-fi
+orig_dir="`pwd`"
 
-if ! cd "$dir"; then
-    echo >&2 "Expected directory $dir was missing"
-    exit 1
-fi
+for supportconfig in "$@"; do
+    cd "$orig_dir"
 
-if ! [ -e basic-environment.txt ]; then
-    echo >&2 "ERROR: basic-environment.txt missing - are you sure this is a supportconfig?"
-    exit 1
-fi
+    if ! dir=$(up "$supportconfig"); then
+        exit $?
+    fi
 
-split-supportconfig *.txt
+    if ! cd "$dir"; then
+        echo >&2 "Expected directory $dir was missing"
+        exit 1
+    fi
+
+    if ! [ -e basic-environment.txt ]; then
+        echo >&2 "ERROR: basic-environment.txt missing - are you sure this is a supportconfig?"
+        exit 1
+    fi
+
+    split-supportconfig *.txt
+done
